### ISSUE TITLE
[FtpStream] Missing "first" file in directory

### ISSUE THREAD

**Issue by DerDu** [emersion/php-wrappers#1]
`dir_readdir()` uses `next()` to read `dir_list` array.. 

.. unfortunate this skips the first entry :-/

so if `dir_pos === 0` than `current()` should be used instead

> next() behaves like current(), with one difference. It advances the internal array pointer one place forward **before** returning the element value. That means it returns the next array value and advances the internal array pointer by one.

**Comment by emersion** [comment]
Can you send a PR?

**Comment by DerDu** [comment]
PR: #2
